AUG:
  MEAN:
  - 0.4712
  - 0.4499
  - 0.4031
  STD:
  - 0.2726
  - 0.2634
  - 0.2794
  TEST_CROP: true
DATA:
  NUM_WORKERS: 2
  IMG_SIZE: 224
  TEST:
    BATCH_SIZE: 1
    DATASET_NAMES:
      - fungi
    DATASET_ROOTS:
      - /speech/dbwork/mul/spielwiese/delafarr/fungi/images/
    EPISODE_DESCR_CONFIG:
      #MAX_NUM_QUERY: 100000
      MIN_EXAMPLES_IN_CLASS: 20
      NUM_QUERY: 10
      NUM_SUPPORT: 50
      NUM_TASKS_PER_EPOCH: 1
      NUM_WAYS: 10
      SEQUENTIAL_SAMPLING: 0
      USE_BILEVEL_HIERARCHY: false
      USE_DAG_HIERARCHY: false
      REPLACEMENT: true
GPU_ID: 0
IS_TRAIN: 0
MODEL:
  BACKBONE: DINO_v2
  BINARY_MASK: true
  CLASSIFIER: LR
  CLASSIFIER_PARAMETERS: []
  EPOCH_MASK: 88
  LR_MASK: 0.004609225155791903
  NAME: evaluation
  N_LOWEST: 0
  REG_MASK: 0.00011634981264820174
  TYPE: mask
OUTPUT: output_files/one_task_50_shots_baseline/
SEED: 0