AUG:
  MEAN:
  - 0.4712
  - 0.4499
  - 0.4031
  STD:
  - 0.2726
  - 0.2634
  - 0.2794
  TEST_CROP: true
DATA:
  IMG_SIZE: 224
  NUM_WORKERS: 2
  TEST:
    BATCH_SIZE: 1
    DATASET_NAMES:
    - mscoco
    DATASET_ROOTS:
    - /speech/dbwork/mul/spielwiese/delafarr/mscoco/imgs_g/
    EPISODE_DESCR_CONFIG:
      MAX_NUM_QUERY: 100000
      MIN_EXAMPLES_IN_CLASS: 20
      NUM_SUPPORT: 65
      NUM_TASKS_PER_EPOCH: 1
      NUM_WAYS: 40
      REPLACEMENT: true
      SEQUENTIAL_SAMPLING: 0
      USE_BILEVEL_HIERARCHY: false
      USE_DAG_HIERARCHY: false
GPU_ID: 0
IS_TRAIN: 0
MODEL:
  BACKBONE: clip
  BINARY_MASK: true
  CLASSIFIER: LR
  CLASSIFIER_PARAMETERS: []
  EPOCH_MASK: 43
  LR_MASK: 2.995080297934221e-05
  NAME: evaluation
  N_LOWEST: 0
  REG_MASK: 0.2731373391119473
  TYPE: mask
OUTPUT: output_files/baseline/
SEED: 0
