AUG:
  MEAN:
  - 0.4712
  - 0.4499
  - 0.4031
  STD:
  - 0.2726
  - 0.2634
  - 0.2794
  TEST_CROP: true
DATA:
  IMG_SIZE: 224
  NUM_WORKERS: 2
  TEST:
    BATCH_SIZE: 1
    DATASET_NAMES:
    - traffic_signs
    DATASET_ROOTS:
    - /speech/dbwork/mul/spielwiese/delafarr/traffic_signs/GTSRB/Final_Training/Images/
    EPISODE_DESCR_CONFIG:
      MAX_NUM_QUERY: 100000
      MIN_EXAMPLES_IN_CLASS: 20
      NUM_SUPPORT: 65
      NUM_TASKS_PER_EPOCH: 1
      NUM_WAYS: 40
      REPLACEMENT: true
      SEQUENTIAL_SAMPLING: 0
      USE_BILEVEL_HIERARCHY: false
      USE_DAG_HIERARCHY: false
GPU_ID: 0
IS_TRAIN: 0
MODEL:
  BACKBONE: clip
  BINARY_MASK: true
  CLASSIFIER: LR
  CLASSIFIER_PARAMETERS: []
  EPOCH_MASK: 55
  LR_MASK: 0.013864042207215582
  NAME: evaluation
  N_LOWEST: 0
  REG_MASK: 0.01703363158819841
  TYPE: mask
OUTPUT: output_files/one_task_50_shots_baseline/
SEED: 0
