AUG:
  MEAN:
  - 0.4712
  - 0.4499
  - 0.4031
  STD:
  - 0.2726
  - 0.2634
  - 0.2794
  TEST_CROP: true
DATA:
  IMG_SIZE: 224
  NUM_WORKERS: 2
  TEST:
    BATCH_SIZE: 1
    DATASET_NAMES:
    - aircraft
    DATASET_ROOTS:
    - /speech/dbwork/mul/spielwiese/delafarr/fgvc-aircraft-2013b/data/converted/converted/
    EPISODE_DESCR_CONFIG:
      MAX_NUM_QUERY: 100000
      MIN_EXAMPLES_IN_CLASS: 20
      NUM_SUPPORT: 65
      NUM_TASKS_PER_EPOCH: 1
      NUM_WAYS: 15
      REPLACEMENT: true
      SEQUENTIAL_SAMPLING: 0
      USE_BILEVEL_HIERARCHY: false
      USE_DAG_HIERARCHY: false
GPU_ID: 0
IS_TRAIN: 0
MODEL:
  BACKBONE: clip
  CLASSIFIER: LR
  CLASSIFIER_PARAMETERS: []
  EPOCH_MASK: 87
  LR_MASK: 5.5789464791657955e-09
  NAME: evaluation
  REG_MASK: 2.5883619069958795e-05
  TYPE: Episodic_Model
OUTPUT: output_files/LR/
SEED: 0
