AUG:
  MEAN:
    - 0.4712
    - 0.4499
    - 0.4031
  STD:
    - 0.2726
    - 0.2634
    - 0.2794
  TEST_CROP: true
DATA:
  IMG_SIZE: 224
  TEST:
    BATCH_SIZE: 1
    DATASET_NAMES:
      - mscoco
    DATASET_ROOTS:
      - /home/datasets/mscoco/imgs_g/
    EPISODE_DESCR_CONFIG:
      MAX_NUM_QUERY: 100000
      MIN_EXAMPLES_IN_CLASS: 20
      #NUM_QUERY: 15
      NUM_SUPPORT: 5
      NUM_TASKS_PER_EPOCH: 50
      NUM_WAYS: 40
      SEQUENTIAL_SAMPLING: 0
      USE_BILEVEL_HIERARCHY: false
      USE_DAG_HIERARCHY: false
      REPLACEMENT: true
GPU_ID: 0
IS_TRAIN: 0
MODEL:
  BACKBONE: DINO_v2
  CLASSIFIER: LR
  CLASSIFIER_PARAMETERS: []
  NAME: evaluation
  TYPE: fewshot_LORA
  LR_HEAD: 0.01
  LR_LORA: 0.01
  EPOCH_HEAD: 0
  EPOCH_LORA: 0
  OPTIMIZER_HEAD: scikit
  OPTIMIZER_LORA: adam
  REGULARIZATION_HEAD: 1.0
  REGULARIZATION_LORA: 0.0
#OUTPUT: ../scikit_x_lora_2/
OUTPUT: ../test/
SEED: 0
